Repository swagger-api/swagger-editor, pull requests merged in 2022-02, with the labels that each got.

#2879 feat(docker): add support for URL environment variable
  README.md
  docker-run.sh
Labels: type: enhancement, version: 4.x, docker

#2882 chore(package-lock): convert to lockfileVersion@2
  .nvmrc
  package-lock.json
Labels: type: enhancement, cat: dependencies

#2884 ci(GA): optimize workflows
  .github/workflows/nodejs.yml
  config/jest/jest.artifact-es-bundle-core.config.js
  config/jest/jest.artifact-es-bundle.config.js
  config/jest/jest.artifact.config.js
  package-lock.json
  package.json
Labels: type: enhancement

#2886 build(webpack): eliminate duplicates in build fragments
  webpack/_config-builder.js
Labels: type: enhancement

#2887 docs(README): change supported Node.js versions
  README.md
Labels: cat: documentation

#2888 chore(deps-dev): bump eslint from 7.32.0 to 8.8.0
  .eslintrc
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  src/plugins/editor-autosuggest-keywords/keyword-map.js
  src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js
  src/plugins/editor-autosuggest-snippets/snippets.js
  src/plugins/editor/components/editor.jsx
  src/plugins/editor/editor-plugins/json-to-yaml.js
  src/plugins/json-schema-validator/validator/path-translator.js
  src/plugins/local-storage/petstore.js
  src/plugins/split-pane-mode/components/split-pane-mode.jsx
  src/plugins/validate-semantic/validators/2and3/refs.js
  src/plugins/validate-semantic/validators/oas3/components.js
  src/standalone/topbar/DropdownMenu.js
  src/standalone/topbar/topbar.jsx
  test/unit/mocks/ace.js
  test/unit/plugins/editor-metadata/index.js
  test/unit/plugins/validate-semantic/2and3/paths.js
Labels: cat: dependencies

#2894 refactor: utilize error boundaries via safe-render plugin
  src/index.js
Labels: type: enhancement

#2893 fix: autocompletion regex for OAS3 component names
  src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js
Labels: type: bug

#2911 chore(security): fix security vulnerabilities in deps
  package-lock.json
Labels: cat: dependencies, security fix

#2912 chore(security): resolve security vulnerability in ajv
  package-lock.json
  package.json
  src/plugins/json-schema-validator/validator/index.js
Labels: cat: dependencies, security vulnerability

#2916 chore(nvmrc): set Node.js version to 16.13.2
  .nvmrc
Labels: type: enhancement, cat: dependencies

#2917 chore(package): consolidate cypress scripts
  .github/workflows/nodejs.yml
  cypress.json
  package-lock.json
  package.json
Labels: type: enhancement

#2918 chore(release): amend release hooks
  release/.release-it.json
Labels: type: enhancement

#2919 fix(build): bundle React just once
  package-lock.json
  package.json
  webpack/_config-builder.js
Labels: type: bug

#2921 chore(deps): bump react-dropzone from 4.2.11 to 12.0.4
  package-lock.json
  package.json
  src/layout.jsx
  test/e2e/.eslintrc
  test/e2e/fixtures/petstore.openapi.yaml
  test/e2e/fixtures/rejected.file.1
  test/e2e/fixtures/rejected.file.2
  test/e2e/support/commands.js
  test/e2e/tests/layout.js
  test/unit/layout.js
Labels: type: enhancement, cat: dependencies
