Repository swagger-api/swagger-editor, pull requests merged in 2022-08, with the labels that each got.

#3323 refactor(swagger-ui-adapter): amend when loader is shown
  package-lock.json
  src/plugins/editor-content-type/index.js
  src/plugins/editor-content-type/selectors.js
  src/plugins/editor-preview/index.js
  src/plugins/swagger-ui-adapter/wrap-components/BaseLayout.jsx
Labels: type: enhancement, swagger-editor@next

#3327 refactor(edit-menu): convert format using async thunk
  src/plugins/top-bar/components/EditMenu/EditMenu.jsx
  src/plugins/top-bar/components/EditMenu/EditMenuHandler.jsx
Labels: type: enhancement, swagger-editor@next

#3332 fix(validate-semantic): allow mapping param under x-* keys
  package-lock.json
  src/plugins/validate-semantic/selectors.js
  test/unit/plugins/validate-semantic/oas3/refs.js
Labels: type: bug

#3211 Changes default Petstore version to v3 (OAS 3.0)
  dev-helpers/index.html
  package.json
  src/plugins/default-definitions/index.js
  src/plugins/local-storage/index.js
  src/plugins/local-storage/petstore.js
  src/standalone/topbar/topbar.jsx
  test/e2e/tests/bugs/1862.js
  test/e2e/tests/definition-loading.js
  webpack/e2e.babel.js
Labels: type: enhancement, type: feature

#3360 feat: add valid forward spec version detection
  package-lock.json
  package.json
  src/plugins/editor-content-type/actions.js
Labels: type: enhancement, swagger-editor@next

#3364 chore(deps): update monaco-editor-core to v0.34.0
  package-lock.json
  package.json
  src/plugins/editor-monaco/components/MonacoEditor/MonacoEditor.jsx
Labels: cat: dependencies, swagger-editor@next

#3385 Promote awareness of SwaggerEditor@Next and add About Section
  src/standalone/styles/topbar.less
  src/standalone/topbar/topbar.jsx
  test/e2e/tests/topbar.js
Labels: type: enhancement, swagger-editor, version: 4.x

#3396 feat(deps): integrate ApiDOM@0.41.0
  package-lock.json
  package.json
Labels: cat: dependencies, type: feature, swagger-editor@next
