Repository swagger-api/swagger-editor, pull requests merged in 2022-04, with the labels that each got.

#2998 build: migrate to webpack@5
  dev-helpers/index.html
  package-lock.json
  package.json
  test/build-artifacts/es-bundle-core.js
  webpack/_config-builder.js
  webpack/bundle.babel.js
  webpack/core.babel.js
  webpack/dev.babel.js
  webpack/es-bundle-core.babel.js
  webpack/es-bundle.babel.js
  webpack/standalone.babel.js
  webpack/stylesheets.babel.js
Labels: type: enhancement, version: 4.x

#3019 chore(deps-dev): update development deps
  package-lock.json
  package.json
Labels: cat: dependencies

#3024 Set permissions for GitHub actions
  .github/workflows/docker-image-check.yml
  .github/workflows/nodejs.yml
Labels: type: enhancement

#3027 build: add support for Create React App
  webpack/es-bundle.babel.js
Labels: type: enhancement
