Repository swagger-api/swagger-editor, pull requests merged in 2022-10, with the labels that each got.

#3529 feat: add better support for OpenAPI 3.0.x editing experience
  package-lock.json
  package.json
Labels: cat: dependencies, type: feature, swagger-editor@next

#3531 Fixed typos in topbar.jsx
  src/standalone/topbar/topbar.jsx
Labels: type: enhancement

#3537 Refactor nodejs.yml workflow
  .github/workflows/nodejs.yml
Labels: type: enhancement

#3545 feat: add better support for OpenAPI 3.0.x editing experience
  package-lock.json
  package.json
Labels: type: enhancement, swagger-editor@next

#3561 feat: add better support for OpenAPI 3.0.x editing experience
  package-lock.json
  package.json
Labels: swagger-editor@next

#3575 chore(package-lock): fix fsevents installation
  package-lock.json
Labels: cat: dependencies, swagger-editor@next

#3586 feat: add full support of OpenAPI 3.0.x editing experience
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#3595 feat(browserslist): produce artifacts against modern desktop browsers
  .browserslistrc
Labels: type: enhancement, swagger-editor@next

#3597 chore(dependabot): ignore react-scripts
  .github/dependabot.yaml
Labels: type: enhancement, cat: dependencies

#3600 feat: add support for full OpenAPI 3.1.0 editing experience
  package-lock.json
  package.json
Labels: cat: dependencies, type: feature, swagger-editor@next
