Repository swagger-api/swagger-editor, pull requests merged in 2022-06, with the labels that each got.

#3089 chore(package-lock): regenerate to v2 format after release
  package-lock.json
Labels: type: enhancement, cat: dependencies

#3083 fix(topbar): display the convert to OpenAPI 3 button when needed
  src/standalone/topbar-menu-edit-convert/components/convert-definition-menu-item.jsx
Labels: type: bug

#3108 chore(dependabot): update config for next branch
  .github/dependabot.yaml
Labels: cat: dependencies

#3123 chore(dependabot): set labels to distinguish from next branch PRs
  .github/dependabot.yaml
Labels: cat: dependencies

#3152 ci(dependabot-merge): don't wait for Jenkins job anymore
  .github/workflows/dependabot-merge.yml
Labels: cat: dependencies

#3159 docs(architecture): provide high level architecture document
  docs/architecture.md
Labels: cat: documentation, swagger-editor@next

#3167 ci(ga): update nightly build cron schedule
  .github/workflows/nightly-build.yml
Labels: swagger-editor@next, github_actions

#3175 feat: skip validation for unrecognized specifications/formats
  package-lock.json
  package.json
  src/plugins/editor-monaco/utils/monaco-action-apidom-deref.js
  src/plugins/editor-monaco/workers/apidom/ApiDOMWorker.js
  src/plugins/editor-monaco/workers/apidom/adapters/SemanticTokensAdapter.js
  src/plugins/topbar/actions/save-as-json-or-yaml/index.js
Labels: type: enhancement

#3194 feat: integrate ApiDOM@0.32.0 with new AsyncAPI linting rules
  package-lock.json
  package.json
Labels: type: feature, swagger-editor@next

#3201 feat: integrate ApiDOM@0.33.0
  package-lock.json
  package.json
Labels: type: feature, swagger-editor@next

#3200 feat: custom env for SWAGGER_URL and SWAGGER_FILE
  .env
  README.md
  public/static/petstore-oas3.yml
  src/index.jsx
Labels: type: feature, javascript, swagger-editor@next
