Repository swagger-api/swagger-editor, pull requests merged in 2022-11, with the labels that each got.

#3615 chore: add better support for Windows dev setup
  .gitattributes
  .gitmodules
  .prettierrc
Labels: type: enhancement, swagger-editor@next

#3616 feat: add support for AsyncAPI 2.5.0
  .env
  package-lock.json
  package.json
  src/plugins/editor-content-fixtures/index.js
  src/plugins/editor-content-fixtures/selectors/selectAsyncAPI250JSON.js
  src/plugins/editor-content-fixtures/selectors/selectAsyncAPI250PetstoreJSON.js
  src/plugins/top-bar/components/EditMenu/EditMenuHandler.jsx
  src/plugins/top-bar/components/EditMenu/items/LoadAsyncAPI24FixtureMenuItem.jsx
  src/plugins/top-bar/components/EditMenu/items/LoadAsyncAPI24PetstoreFixtureMenuItem.jsx
  test/cypress/fixtures/streetlights-kafka.yml
  test/cypress/integration/plugin.editor-persistence.spec.js
  test/cypress/integration/plugin.editor-preview-asyncapi.spec.js
  test/cypress/integration/plugin.editor-preview-swaggerui.spec.js
  test/cypress/integration/plugin.top-bar.spec.js
  test/cypress/support/commands.js
Labels: type: enhancement, type: feature, swagger-editor@next

#3618 chore(deps): bump @swagger-api/apidom packages to 0.56.0
  package-lock.json
  package.json
Labels: cat: dependencies, javascript, swagger-editor@next

#3636 chore(deps): update dependencies manually
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#3623 feat(topbar): allow to configure components present in Topbar
  dev-helpers/index.html
  src/standalone/index.js
  src/standalone/topbar-new-editor-button/components/NewEditorButton.jsx
  src/standalone/topbar-new-editor-button/index.js
  src/standalone/topbar/assets/logo_small.svg
  src/standalone/topbar/components/AboutMenu.jsx
  src/standalone/topbar/components/DropdownMenu.jsx
  src/standalone/topbar/components/Topbar.jsx
  src/standalone/topbar/index.js
  test/e2e/static/index.html
Labels: type: enhancement

#3650 ci: limit workflows based on branches
  .github/workflows/deploy-gh-pages.yml
  .github/workflows/deploy-rancher.yml
Labels: type: enhancement, github_actions

#3648 Add About Menu to TopBar for swagger-editor@next
  package.json
  src/plugins/top-bar/components/AboutMenu/AboutMenu.jsx
  src/plugins/top-bar/components/Logo/Logo.jsx
  src/plugins/top-bar/components/TopBar/TopBar.jsx
  src/plugins/top-bar/index.js
  test/cypress/integration/plugin.top-bar.spec.js
Labels: type: enhancement, swagger-editor@next

#3654 chore(docker): add support for multi platform docker image
  .github/workflows/deploy-rancher.yml
Labels: type: enhancement, docker, swagger-editor@next

#3655 ci(deploy-rancher): fix typo in platform list
  .github/workflows/deploy-rancher.yml
Labels: type: enhancement, docker, swagger-editor@next

#3661 fix: introduce various bug fixes in linting via ApiDOM@0.56.1
  package-lock.json
  package.json
Labels: type: enhancement, swagger-editor@next

#3670 chore(deps): update dependencies
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#3672 ci: separate docker image build/push and deploy to separate workflows
  .github/workflows/deploy-rancher.yml
  .github/workflows/docker-build-push.yml
Labels: docker, swagger-editor@next

#3673 ci: reflect changes to GitHub workflows from master
  .github/workflows/deploy-rancher.yml
  .github/workflows/docker-build-push.yml
Labels: type: enhancement, swagger-editor@next

#3674 ci: enable Rancher deploy workflow
  .github/workflows/deploy-rancher.yml
  .github/workflows/docker-build-push.yml
Labels: swagger-editor@next

#3675 ci: deploy SwaggerEditor@next to Rancher on successful release
  .github/workflows/deploy-rancher.yml
  .github/workflows/release.yml
Labels: docker, swagger-editor@next

#3676 ci: reflect changes to GitHub workflows from master
  .github/workflows/deploy-rancher.yml
  .github/workflows/release.yml
Labels: docker, swagger-editor@next

#3677 fix: fix AsyncAPI 2.x Operation.security field lint rules
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#3688 ci(release): test release dry run to determine the version
  .github/workflows/release.yml
Labels: type: enhancement, swagger-editor@next

#3689 ci(release): add proper version to npm dist fragments
  .github/workflows/docker-build-push.yml
  .github/workflows/release.yml
Labels: type: enhancement, swagger-editor@next

#3703 ci(dependabot-merge): replace non-functioning merge action
  .github/workflows/dependabot-merge.yml
Labels: type: enhancement, cat: dependencies
