Repository swagger-api/swagger-editor, pull requests merged in 2022-03, with the labels that each got.

#2936 docs(README): remove dependencies badges
  README.md
Labels: cat: dependencies, cat: documentation

#2937 chore(deps): fix security vulnerabilities
  package-lock.json
Labels: cat: dependencies, security vulnerability, security fix

#2932 Fix typo in *.js files
  src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js
Labels: type: enhancement

#2965 Fix Missing npm script
  package.json
Labels: type: enhancement, version: 4.x

#2984 chore(package-lock): transform to lockfileVersion@v2
  package-lock.json
Labels: cat: dependencies, security fix

#2985 fix(build): fix missing code fragments in build fragments
  config/jest/jest.artifact.config.js
  config/jest/jest.unit.config.js
  package-lock.json
  package.json
  webpack/_config-builder.js
Labels: type: bug, type: enhancement, version: 4.x
