Repository swagger-api/swagger-editor, pull requests merged in 2023-11, with the labels that each got.

#4529 chore(deps-dev): bump @testing-library/jest-dom from 5.17.0 to 6.1.4
  package-lock.json
  package.json
Labels: type: enhancement, cat: dependencies, swagger-editor@next

#4554 fix: fix handling cycles in OpenAPI 3.1.0 definitions
  package-lock.json
  package.json
Labels: type: bug, cat: dependencies, swagger-editor@next

#4556 ci(deploy-rancher): track deployments to editor-next.swagger.io
  .github/workflows/deploy-rancher.yml
Labels: type: enhancement, swagger-editor@next

#4557 ci(deploy-rancher): track deployments to editor-next.swagger.io
  .github/workflows/deploy-rancher.yml
Labels: type: enhancement, version: 4.x

#4566 enable showExtensions of OAS2.0/OAS3.0
  src/App.jsx
Labels: swagger-editor@next

#4586 fix(editor-preview-asyncapi): use stable versions of AsyncAPI tooling
  package-lock.json
  package.json
Labels: cat: dependencies, type: regression, type: upstream bug, swagger-editor@next

#4587 chore(deps-dev): bump prettier from 3.0.3 to 3.1.0
  .eslintrc
  package-lock.json
  package.json
  src/plugins/editor-content-type/selectors.js
  src/plugins/editor-monaco-language-apidom/language/actions/dereference.js
  src/plugins/editor-preview-asyncapi/components/EditorPreviewAsyncAPI/EditorPreviewAsyncAPI.jsx
  src/plugins/top-bar/actions/convert-openapi-20-to-openapi-30x.js
  src/plugins/top-bar/actions/fetch-openapi2-generator-client-list.js
  src/plugins/top-bar/actions/fetch-openapi2-generator-server-list.js
  src/plugins/top-bar/actions/fetch-openapi3-generator-client-list.js
  src/plugins/top-bar/actions/fetch-openapi3-generator-server-list.js
  src/plugins/top-bar/actions/generate-client-code-from-openapi-20.js
  src/plugins/top-bar/actions/generate-client-code-from-openapi-3.js
  src/plugins/top-bar/actions/generate-server-code-from-openapi-20.js
  src/plugins/top-bar/actions/generate-server-code-from-openapi-3.js
  src/plugins/top-bar/actions/import-url.js
  src/plugins/top-bar/components/FileMenu/items/SaveAsMenuItem.jsx
Labels: cat: dependencies, swagger-editor@next

#4588 feat(editor-preview-asyncapi): add support for protobufs
  package-lock.json
  package.json
  src/plugins/editor-preview-asyncapi/actions.js
Labels: type: feature, swagger-editor@next

#4624 fix(monaco-editor): pin monaco-editor + VSCode combo
  package-lock.json
  package.json
Labels: cat: dependencies, type: upstream bug, swagger-editor@next

#4625 fix(editor-monaco): re-introduce Go To Symbol contextual menu item
  src/plugins/editor-monaco/after-load.js
  src/plugins/editor-monaco/monaco-contribution/actions/go-to-symbol.js
  src/plugins/editor-monaco/monaco-contribution/index.js
Labels: type: upstream bug, swagger-editor@next

#4626 fix(editor-monaco): display commands palette dialog
  .eslintrc
  src/plugins/editor-monaco/monaco-contribution/index.js
Labels: type: upstream bug, swagger-editor@next

#4627 feat: add initial support for OpenAPI 2.0
  package-lock.json
  package.json
  src/plugins/editor-monaco-language-apidom/language/providers/DiagnosticsProvider.js
  src/plugins/editor-monaco/themes/se-vs-dark.js
  src/plugins/editor-monaco/themes/se-vs-light.js
Labels: type: feature, swagger-editor@next

#4629 feat: integrate swagger-ui-react@5.10.3
  package-lock.json
  package.json
Labels: type: enhancement, cat: dependencies, swagger-editor@next
