Repository swagger-api/swagger-editor, pull requests merged in 2023-01, with the labels that each got.

#3755 fix(dereference): fix serialization of dereferenced definitions
  package-lock.json
  package.json
Labels: cat: dependencies, type: upstream bug, swagger-editor@next

#3772 chore(deps-dev): update number of dev deps
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#3773 fix: fix issues in JSON detection regexp
  package-lock.json
  package.json
Labels: type: bug, swagger-editor@next

#3781 chore(deps-dev): update number of dev deps
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#3783 fix(validate-semantic): narrow allOperations selector
  src/plugins/validate-semantic/selectors.js
Labels: type: enhancement, cat: validation

#3769 Fix TypeError when reading operationId
  src/plugins/validate-semantic/validators/2and3/operations.js
Labels: type: bug, version: 4.x
