Repository swagger-api/swagger-editor, pull requests merged in 2023-10, with the labels that each got.

#4471 fix: use uppercase format for x-frame-options header value
  nginx.conf
Labels: type: enhancement, cat: docker, version: 4.x, docker

#4472 chore(deps): update swagger-ui & swagger-client
  package-lock.json
  package.json
Labels: version: 4.x

#4473 chore(deps): update ApiDOM and swagger-ui-react
  package-lock.json
  package.json
Labels: cat: dependencies, swagger-editor@next

#4447 feat(monaco-language-apidom): switch to apidom-reference validation
  src/plugins/editor-monaco-language-apidom/language/ApiDOMWorker.js
Labels: type: feature, swagger-editor@next
