Repository swagger-api/swagger-editor, pull requests merged in 2024-01, with the labels that each got.

#4686 feat: enhance editing experience for OpenAPI 2.0
  package-lock.json
  package.json
Labels: type: feature, swagger-editor@next

#4689 feat: integrate monaco-editor@0.45.0
  package-lock.json
  package.json
  src/plugins/editor-preview-swagger-ui/components/EditorPreviewSwaggerUI/EditorPreviewSwaggerUI.jsx
  src/plugins/editor-preview-swagger-ui/components/EditorPreviewSwaggerUI/_editor-preview-swagger-ui.scss
  src/plugins/editor-preview-swagger-ui/components/_all.scss
  src/plugins/editor-preview-swagger-ui/index.js
  src/plugins/layout/components/Layout/_layout.scss
  src/styles/main.scss
Labels: cat: dependencies, type: feature, swagger-editor@next

#4691 feat: add support for React@18
  README.md
  package-lock.json
  package.json
  src/index.jsx
Labels: cat: dependencies, type: feature, swagger-editor@next

#4692 docs(SBOM): use GitHub integrated SBOM
  README.md
  sbom.spdx
Labels: type: enhancement, cat: documentation

#4706 ci: fix labels in workflow files
  .github/workflows/nightly-build.yml
  .github/workflows/nodejs.yml
Labels: type: enhancement, version: 4.x

#4707 chore(deps-dev): bump @babel/plugin-transform-runtime to 7.23.7
  package-lock.json
  package.json
Labels: cat: dependencies, version: 4.x

#4684 fix: Fix typo s/Muliple/Multiple/
  src/plugins/default-definitions/index.js
  test/e2e/static/documents/petstore.swagger.yaml
Labels: type: enhancement, version: 4.x

#4708 fix(editor-content-fixtures): fix typo in OpenAPI 2.0
  src/plugins/editor-content-fixtures/selectors/selectOpenAPI20PetstoreYAML.js
Labels: type: enhancement, swagger-editor@next

#4719 chore: Fix multiple typos
  src/plugins/json-schema-validator/validator/shared.js
  test/unit/plugins/validate-semantic/2and3/paths.js
  test/unit/standalone/topbar-insert/form-validation.js
Labels: version: 4.x

#4637 fix(petstore): Update petstore to conform with OpenAPI 3.0.3 spec
  src/plugins/default-definitions/index.js
Labels: type: enhancement, version: 4.x

#4728 fix(content-fixtures): update to conform with OpenAPI 3.0.3 spec
  src/plugins/editor-content-fixtures/selectors/selectOpenAPI20PetstoreYAML.js
  src/plugins/editor-content-fixtures/selectors/selectOpenAPI303PetstoreYAML.js
  src/plugins/editor-content-fixtures/selectors/selectOpenAPI310PetstoreYAML.js
Labels: type: enhancement, swagger-editor@next

#4738 ci: fix CICD pipeline by updating release-it
  .github/dependabot.yaml
  package-lock.json
  package.json
Labels: type: enhancement, version: 4.x

#4745 fix(json-schema-validator): propertly handle unknown definition
  src/plugins/json-schema-validator/index.js
Labels: type: bug, version: 4.x

#4747 chore(deps-dev): update development dependencies
  package-lock.json
  package.json
Labels: cat: dependencies, version: 4.x

#4749 fix: eliminate regressions caused by using React@18
  package-lock.json
  package.json
  patches/react-ace+4.4.0.patch
  patches/react-transition-group+1.2.1.patch
  src/plugins/editor/components/editor.jsx
  test/mocha/mocks/ace.js
Labels: type: regression, version: 4.x

#4777 feat: add complete editing experience for OpenAPI 2.0
  package-lock.json
  package.json
Labels: type: feature, swagger-editor@next
