Repository swagger-api/swagger-editor, pull requests merged in 2025-03, with the labels that each got.

#5388 fix(security): fix CVE-2025-27152 in Axios
  package-lock.json
  package.json
Labels: cat: dependencies, security vulnerability, security fix

#5389 fix(security): fix CVE-2025-27152 in Axios
  package-lock.json
  package.json
Labels: cat: dependencies, security vulnerability, security fix

#5409 fix(security): address CVE-2025-27789
  package-lock.json
Labels: cat: dependencies, dependencies

#5359 fix: Render AsyncAPI 3+ properly with BaseLayout (#5358)
  src/plugins/swagger-ui-adapter/wrap-components/BaseLayout.jsx
Labels: type: enhancement, swagger-editor@next

#5413 fix(editor-content-fixtures): update Petstore to match SmartBear rules
  src/plugins/editor-content-fixtures/index.js
  src/plugins/editor-content-fixtures/selectors/selectOpenAPI304PetstoreYAML.js
  src/plugins/editor-content-fixtures/selectors/selectOpenAPI311PetstoreYAML.js
  src/plugins/top-bar/components/FileMenu/items/LoadExampleNestedMenu/LoadExampleNestedMenuHandler.jsx
Labels: type: enhancement, swagger-editor@next
